# Generated by Django 5.1.3 on 2024-11-30 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='telegramprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
